### ISSUE TITLE
rake failure after modifications to files

### ISSUE THREAD

**Issue by bjones1** [ThrowTheSwitch/Unity#22]
Running the Unity tests using rake produces a failure the first time I run, followed by success the 2nd time. I'm on Windows 7 64-bit using MinGW, Ruby 1.9.3. The error output: on the first run is below. Running rake again produces all tests passing. The third time produces the error below, etc.

```
C:\Users\bjones\Documents\micro_book\Unity>rake
rm -r build/testparameterized.exe
rm -r build/testparameterized.o
rm -r build/testparameterized.testpass
rm -r build/testparameterized_Runner.c
rm -r build/testparameterized_Runner.o
rm -r build/testsample_cmd.c
rm -r build/testsample_def.c
rm -r build/testsample_mock_cmd.c
rm -r build/testsample_mock_def.c
rm -r build/testsample_mock_new1.c
rm -r build/testsample_mock_new2.c
rm -r build/testsample_mock_param.c
rm -r build/testsample_mock_run1.c
rm -r build/testsample_mock_run2.c
rm -r build/testsample_mock_yaml.c
rm -r build/testsample_new1.c
rm -r build/testsample_new2.c
rm -r build/testsample_param.c
rm -r build/testsample_run1.c
rm -r build/testsample_run2.c
rm -r build/testsample_yaml.c
rm -r build/testunity.exe
rm -r build/testunity.o
rm -r build/testunity.testpass
rm -r build/testunity_Runner.c
rm -r build/testunity_Runner.o
rm -r build/unity.o
rm -r C:/Users/bjones/Documents/micro_book/Unity/build
C:/Ruby193/bin/ruby.exe -I"lib" -I"C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.0
.2/lib" "C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.0.2/lib/rake/rake_test_load
er.rb" "test/test_*.rb"
Loaded suite C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.0.2/lib/rake/rake_test_
loader
Started
E
===============================================================================
Error: test_ShouldGenerateARunnerByCreatingRunnerWithOptions(TestGenerateTestRun
ner)
  Errno::ENOENT: No such file or directory - build/testsample_def.c
C:/Users/bjones/Documents/micro_book/Unity/auto/generate_test_runner.rb:58:in `i
nitialize'
C:/Users/bjones/Documents/micro_book/Unity/auto/generate_test_runner.rb:58:in `o
pen'
C:/Users/bjones/Documents/micro_book/Unity/auto/generate_test_runner.rb:58:in `g
enerate'
C:/Users/bjones/Documents/micro_book/Unity/auto/generate_test_runner.rb:48:in `r
un'
C:/Users/bjones/Documents/micro_book/Unity/test/test_generate_test_runner.rb:40:
in `block in test_ShouldGenerateARunnerByCreatingRunnerWithOptions'
C:/Users/bjones/Documents/micro_book/Unity/test/test_generate_test_runner.rb:39:
in `each_pair'
C:/Users/bjones/Documents/micro_book/Unity/test/test_generate_test_runner.rb:39:
in `test_ShouldGenerateARunnerByCreatingRunnerWithOptions'
     36:              'new2' => { :plugins => [:ignore], :suite_setup => "a_cust
om_setup();", :suite_teardown => "a_custom_teardown();" }
     37:     }
     38:
  => 39:     sets.each_pair do |subtest, options|
     40:       UnityTestRunnerGenerator.new(options).run(TEST_FILE, OUT_FILE + s
ubtest + '.c')
     41:       verify_output_equal(subtest)
     42:       UnityTestRunnerGenerator.new(options).run(TEST_MOCK, OUT_FILE + '
mock_' + subtest + '.c')
===============================================================================
auto/generate_test_runner.rb:58:in `initialize': No such file or directory - bui
ld/testsample_cmd.c (Errno::ENOENT)
        from auto/generate_test_runner.rb:58:in `open'
        from auto/generate_test_runner.rb:58:in `generate'
        from auto/generate_test_runner.rb:48:in `run'
        from auto/generate_test_runner.rb:315:in `<main>'
E
===============================================================================
Error: test_ShouldGenerateARunnerByPullingCommandlineOptions(TestGenerateTestRun
ner)
  Errno::ENOENT: No such file or directory - build/testsample_cmd.c
C:/Users/bjones/Documents/micro_book/Unity/test/test_generate_test_runner.rb:29:
in `read'
C:/Users/bjones/Documents/micro_book/Unity/test/test_generate_test_runner.rb:29:
in `verify_output_equal'
C:/Users/bjones/Documents/micro_book/Unity/test/test_generate_test_runner.rb:75:
in `test_ShouldGenerateARunnerByPullingCommandlineOptions'
     72:     subtest = 'cmd'
     73:     cmdstr = "ruby auto/generate_test_runner.rb -cexception \"#{TEST_FI
LE}\" \"#{OUT_FILE + subtest + '.c'}\""
     74:     `#{cmdstr}`
  => 75:     verify_output_equal(subtest)
     76:
     77:     cmdstr = "ruby auto/generate_test_runner.rb -cexception \"#{TEST_MO
CK}\" \"#{OUT_FILE + 'mock_' + subtest + '.c'}\""
     78:     `#{cmdstr}`
===============================================================================
auto/generate_test_runner.rb:58:in `initialize': No such file or directory - bui
ld/testsample_yaml.c (Errno::ENOENT)
        from auto/generate_test_runner.rb:58:in `open'
        from auto/generate_test_runner.rb:58:in `generate'
        from auto/generate_test_runner.rb:48:in `run'
        from auto/generate_test_runner.rb:315:in `<main>'
E
===============================================================================
Error: test_ShouldGenerateARunnerByPullingYamlOptions(TestGenerateTestRunner)
  Errno::ENOENT: No such file or directory - build/testsample_yaml.c
C:/Users/bjones/Documents/micro_book/Unity/test/test_generate_test_runner.rb:29:
in `read'
C:/Users/bjones/Documents/micro_book/Unity/test/test_generate_test_runner.rb:29:
in `verify_output_equal'
C:/Users/bjones/Documents/micro_book/Unity/test/test_generate_test_runner.rb:64:
in `test_ShouldGenerateARunnerByPullingYamlOptions'
     61:     subtest = 'yaml'
     62:     cmdstr = "ruby auto/generate_test_runner.rb test/testdata/sample.ym
l \"#{TEST_FILE}\" \"#{OUT_FILE + subtest + '.c'}\""
     63:     `#{cmdstr}`
  => 64:     verify_output_equal(subtest)
     65:
     66:     cmdstr = "ruby auto/generate_test_runner.rb test/testdata/sample.ym
l \"#{TEST_MOCK}\" \"#{OUT_FILE + 'mock_' + subtest + '.c'}\""
     67:     `#{cmdstr}`
===============================================================================
E
===============================================================================
Error: test_ShouldGenerateARunnerByRunningRunnerWithOptions(TestGenerateTestRunn
er)
  Errno::ENOENT: No such file or directory - build/testsample_run1.c
C:/Users/bjones/Documents/micro_book/Unity/auto/generate_test_runner.rb:58:in `i
nitialize'
C:/Users/bjones/Documents/micro_book/Unity/auto/generate_test_runner.rb:58:in `o
pen'
C:/Users/bjones/Documents/micro_book/Unity/auto/generate_test_runner.rb:58:in `g
enerate'
C:/Users/bjones/Documents/micro_book/Unity/auto/generate_test_runner.rb:48:in `r
un'
C:/Users/bjones/Documents/micro_book/Unity/test/test_generate_test_runner.rb:53:
in `block in test_ShouldGenerateARunnerByRunningRunnerWithOptions'
C:/Users/bjones/Documents/micro_book/Unity/test/test_generate_test_runner.rb:52:
in `each_pair'
C:/Users/bjones/Documents/micro_book/Unity/test/test_generate_test_runner.rb:52:
in `test_ShouldGenerateARunnerByRunningRunnerWithOptions'
     49:              'run2' => { :plugins => [:ignore], :suite_setup => "a_cust
om_setup();", :suite_teardown => "a_custom_teardown();" }
     50:     }
     51:
  => 52:     sets.each_pair do |subtest, options|
     53:       UnityTestRunnerGenerator.new.run(TEST_FILE, OUT_FILE + subtest +
'.c', options)
     54:       verify_output_equal(subtest)
     55:       UnityTestRunnerGenerator.new.run(TEST_MOCK, OUT_FILE + 'mock_' +
subtest + '.c', options)
===============================================================================
E
===============================================================================
Error: test_ShouldGenerateARunnerThatUsesParameterizedTests(TestGenerateTestRunn
er)
  Errno::ENOENT: No such file or directory - build/testsample_param.c
C:/Users/bjones/Documents/micro_book/Unity/auto/generate_test_runner.rb:58:in `i
nitialize'
C:/Users/bjones/Documents/micro_book/Unity/auto/generate_test_runner.rb:58:in `o
pen'
C:/Users/bjones/Documents/micro_book/Unity/auto/generate_test_runner.rb:58:in `g
enerate'
C:/Users/bjones/Documents/micro_book/Unity/auto/generate_test_runner.rb:48:in `r
un'
C:/Users/bjones/Documents/micro_book/Unity/test/test_generate_test_runner.rb:87:
in `block in test_ShouldGenerateARunnerThatUsesParameterizedTests'
C:/Users/bjones/Documents/micro_book/Unity/test/test_generate_test_runner.rb:86:
in `each_pair'
C:/Users/bjones/Documents/micro_book/Unity/test/test_generate_test_runner.rb:86:
in `test_ShouldGenerateARunnerThatUsesParameterizedTests'
     83:     sets = { 'param'  => { :plugins => [:ignore], :use_param_tests => t
rue }
     84:     }
     85:
  => 86:     sets.each_pair do |subtest, options|
     87:       UnityTestRunnerGenerator.new(options).run(TEST_FILE, OUT_FILE + s
ubtest + '.c')
     88:       verify_output_equal(subtest)
     89:       UnityTestRunnerGenerator.new(options).run(TEST_MOCK, OUT_FILE + '
mock_' + subtest + '.c')
===============================================================================


Finished in 0.199012 seconds.

5 tests, 0 assertions, 0 failures, 5 errors, 0 pendings, 0 omissions, 0 notifica
tions
0% passed

25.12 tests/s, 0.00 assertions/s
rake aborted!
Command failed with status (1): [ruby -I"lib" -I"C:/Ruby193/lib/ruby/gems/1.9.1/
gems/rake-10.0.2/lib" "C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.0.2/lib/rake/
rake_test_loader.rb" "test/test_*.rb" ]
Tasks: TOP => default => all => scripts
(See full trace by running task with --trace)
```

**Comment by bjones1** [comment]
It's been a while, and I haven't tracked this, so I'm closing.
