### ISSUE TITLE
create runner script: externc option

### ISSUE THREAD

**Issue by DanieleNardi** [ThrowTheSwitch/Unity#569]
Due to a mixed C/C++ project environment, I need to create a test runner with extern "C" declarations, but I have some troubles with the create runner script:
- if I add the option -externc to the command line, it is ignored
- if I use a yml file for configuration in the following form
```
:unity:
  :externc
```
I get the following error:
```
Traceback (most recent call last):
        4: from ../Unity/script/generate_test_runner.rb:463:in `<main>'
        3: from ../Unity/script/generate_test_runner.rb:463:in `reject!'
        2: from ../Unity/script/generate_test_runner.rb:469:in `block in <main>'
        1: from ../Unity/script/generate_test_runner.rb:56:in `grab_config'
../Unity/script/generate_test_runner.rb:56:in `merge!': no implicit conversion of Symbol into Hash (TypeError)
```

I'm using version v2.5.2

**Comment by DanieleNardi** [comment]
I [opened a pull request](https://github.com/ThrowTheSwitch/Unity/pull/570) to provide better explanation and solution to this issue.
