### ISSUE TITLE
Make error in generate_test_runner.rb

### ISSUE THREAD

**Issue by andrewstillie** [ThrowTheSwitch/Unity#670]
I am getting the error below when trying to make the code.  

`$ make
rm -f test1.exe test2.exe
ruby ../../auto/generate_test_runner.rb test/TestProductionCode.c  test/test_runners/TestProductionCode_Runner.c
/usr/share/rubygems/rubygems/util.rb:100:in `glob': no implicit conversion of Hash into Integer (TypeError)
        from /usr/share/rubygems/rubygems/util.rb:100:in `glob_files_in_dir'
        from /usr/share/rubygems/rubygems/specification.rb:779:in `block in each_gemspec'
        from /usr/share/rubygems/rubygems/specification.rb:778:in `each'
        from /usr/share/rubygems/rubygems/specification.rb:778:in `each_gemspec'
        from /usr/share/rubygems/rubygems/specification.rb:807:in `each_spec'
        from /usr/share/rubygems/rubygems/specification.rb:878:in `load_defaults'
        from /usr/share/rubygems/rubygems.rb:1354:in `<top (required)>'
        from <internal:gem_prelude>:4:in `require'
        from <internal:gem_prelude>:4:in `<internal:gem_prelude>'
make: *** [makefile:64: test/test_runners/TestProductionCode_Runner.c] Error 1
`

I am running cygwin
and have this version of ruby installed.

$ ruby -v
ruby 2.3.6p384 (2017-12-14 revision 9808) [x86_64-cygwin]
last_commit=ruby 2.3.3

**Comment by AndersonMartins1** [comment]
Parece que você está enfrentando um erro ao tentar compilar o código, relacionado à execução do script generate_test_runner.rb. O erro sugere que há um problema de conversão de tipo em algum lugar do código Ruby.

Aqui estão algumas etapas que você pode tentar para resolver o problema:

Verifique as Permissões e Configurações do Ruby: Certifique-se de que você tem permissões adequadas para executar o script e que o Ruby está corretamente configurado em seu ambiente.

Atualize o Ruby: Você está usando uma versão relativamente antiga do Ruby (2.3.6). Tente atualizar para uma versão mais recente, se possível, e veja se isso resolve o problema.

Verifique Dependências e Requisitos: O script generate_test_runner.rb pode depender de outras gemas ou bibliotecas Ruby. Certifique-se de que todas as dependências necessárias estejam instaladas e atualizadas corretamente.

Depure o Código: Se possível, revise o código-fonte do script generate_test_runner.rb para entender onde o erro está ocorrendo. Pode haver uma operação de conversão de tipo malformada ou um problema de compatibilidade em algum lugar no código.

Consulte a Documentação: Verifique a documentação do script ou qualquer documentação relacionada ao Unity ou ao ambiente de desenvolvimento que você está usando para ver se há alguma informação sobre problemas semelhantes ou requisitos específicos.

Se nenhuma dessas etapas resolver o problema, pode ser útil procurar ajuda em fóruns de desenvolvedores específicos do Unity ou em comunidades de desenvolvedores Ruby para obter assistência adicional.
